version: 1.1.0.{build}
install:
- cmd: cinst nsis
- ps: |
    $url='http://download.microsoft.com/download/7/B/6/7B629E05-399A-4A92-B5BC-484C74B5124B/dotNetFx40_Client_setup.exe'
    if (!(Test-Path (Split-Path $url -Leaf))) {
        Start-FileDownload $url
    }
assembly_info:
    patch: true
configuration:
- Debug
- Release
before_build:
- nuget restore
cache:
- dotNetFx40_Client_setup.exe
